# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtweb', '0002_auto_20170604_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        
        migrations.DeleteModel(
            name='Post',
        ),
    ]
